### ISSUE TITLE
Approval of the Functional Requirements

### ISSUE THREAD

**Issue by Veromc24** [Veromc24/ISO2-2024-A04#1]
Read carefully the functional requirements listed on the wiki: [Functional Requirements](https://github.com/Veromc24/ISO2-2024-A04/wiki/Functional-Requirements). 

Add your feedback in the comments of this issue and when **all the teammates have give their approval**, the issue will be closed by the coordinator and the next step of the project will start.

**Comment by oblivionwing26** [comment]
After read the requirement list I agree with the list and approve them :)

**Comment by dgms02** [comment]
The functional functionalities seems complete as the general functionalities are general description of the functionalities described in the functionalities of every individual in the project. Some of them will be described in more depth using diagrams.

**Comment by carlosrz022** [comment]
Having given a reading to the funcional requirements, i give my  approval to them.

**Comment by David-Fdz-Liz** [comment]
I agree with the list of requirements after carefully reading them.
