### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by Veromc24** [Veromc24/ISO2-2024-A04#3]
Following today's meeting, each team memer will send  a message to this issue as a way to indicate that their workload has been completed. At the same time the will do a commit. 
Deadline 09/11/2024 - 23:59h.

**Comment by dgms02** [comment]
I have been researching about the functionality of mapping requirements with use cases, the closest thing I have found is to map from a textual analysis (which is basically what is on github) transit it to a glossary (option transit to) and from there transit it again to the requirement that is in the list of requirements, finally from the glosary trnasit it to the the use case with the same name, creating a link in the use case. By doing this we will be able to access from the use case to the glossary with the list of requirements, and from the glossary we will be able to see the attributes of that requirement or requirements. Open to suggestions on how to do this better

**Comment by dgms02** [comment]
I have created the use case diagram for log in and Classify data into categories/Identify and classify/categorize project data. I have also corrected some errors that I have seen in the rest of diagrams, I recommend reviewing them so that if you do not agree with the changes, comment here.

**Comment by oblivionwing26** [comment]
I updated 3 diagrams as we were discussing in order to have a fix structure client<-client.type in every use case diagram

**Comment by oblivionwing26** [comment]
Now 5 new UCs are uploaded with all the corrections in 4 of the previous ones

**Comment by dgms02** [comment]
I have started with UC diagram of the general functionaliries of every user, i havent finished it yet, but if any subdiagram you have to do is already implemented in the general one, use it as a base to do the corresponding subdiagram, or if you think something is not right, feel free to correct it. Keep in mind that this diagram is about the interaction of the client with the app, which means that most of the server's activities are not present, that goes in another diagram

**Comment by carlosrz022** [comment]
I have created 5 new UCDs and uploaded them.

**Comment by dgms02** [comment]
Client functionalities general diagram finished, i have started with server general diagram

**Comment by David-Fdz-Liz** [comment]
I have just made the 7 use case diagrams that corresponded to my part.
