### ISSUE TITLE
This weeks work: IT7-IT12

### ISSUE THREAD

**Issue by Veromc24** [Veromc24/ISO2-2024-A04#5]
This week's work conssits of those iterations, endint the elaboration phase at iteration 9.

**Deadline:**   Saturday 23 at 23:59

**Comment by David-Fdz-Liz** [comment]
IT 3 Completed

**Comment by cmontl** [comment]
IT 5 completed

**Comment by dgms02** [comment]
IT 9 is now completed

**Comment by carlosrz022** [comment]
IT 10 Completed

**Comment by oblivionwing26** [comment]
IT 12 Completed :)

**Comment by David-Fdz-Liz** [comment]
IT 8 Completed

**Comment by cmontl** [comment]
IT 11 completed
